name       : python-cparser
version    : 2.17
release    : 1
source     :
    - https://pypi.python.org/packages/be/64/1bb257ffb17d01f4a38d7ce686809a736837ad4371bcc5c42ba7a715c3ac/pycparser-2.17.tar.gz : 0aac31e917c24cb3357f5a4d5566f2cc91a19ca41862f6c3c22dc60a629673b6
license    : BSD-3-Clause
component  : programming.python
summary    : pycparser is a complete parser of the C language
description: |
    pycparser is a complete parser of the C language
builddeps  :
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
